### ISSUE TITLE
question: managed packages

### ISSUE THREAD

**Issue by tsadigovAgmail** [nawforce/apex-assist#11]
I can not make this work for references to managed package. We do not have source for it so your parser will not be able to parse to get metadata. I installed package to the scratch org. Is there a way to fetch definitions?

**Comment by nawforce** [comment]
Hi Tural,

At the moment it does not have the ability to download metadata although I am working on this so at the moment so it should be possible fairly soon. What you can do though is declare the namespace of the managed package so you wont see errors for it. To do this add this to the end of your sfdx-project.json file. 

```
"plugins": {
    "dependencies": [
        {"namespace": "aa"}
    ]
}
```

This just tells the extension to ignore the use of metadata in the 'aa' namespace and assume it is OK. 

Regards
Kev

**Comment by nawforce** [comment]
You can now download metadata from an org, little demo at [youtu.be/B4lznOZ7Wts](https://t.co/PnI9NvkPcQ).
