### ISSUE TITLE
"ApexAssist server failed to start, code: 0, signal: 0" when saving JSON

### ISSUE THREAD

**Issue by PawelWozniak** [nawforce/apex-assist#2]
When I am using VSCode build in Terminal very often message "ApexAssist server failed to start, code: 0, signal: 0" pop up.
Correction it seems that it happens when I have JSON file open. In this case sfdx-project.json. As I have autosave active each switch between file and terminal initiates save and this error message.
![image](https://user-images.githubusercontent.com/5740564/113939765-acb49280-97fc-11eb-923c-04c7e6c43bcd.png)

**Comment by nawforce** [comment]
Thanks for reporting this. There is auto-restart handling hooked into changes being made to sfdx-project.json. Looks like that needs a bit of improving to only re-start if a change is made that is interesting to the server. The error handling is not giving much of a clue here about why the restart failed, could you perhaps check the output panel if it happens again and see if more info is available. It may just be that rapid restarting is causing some issue.

**Comment by PawelWozniak** [comment]
I can constantly recreate this error but when cleared logs, recreated and reviewed all logs 
![image](https://user-images.githubusercontent.com/5740564/114531771-7d62b300-9c4c-11eb-92b4-227ed9a250f3.png)
nothing is added to any of them.

**Comment by nawforce** [comment]
Thanks for taking a look at that, I had forgotten that might be hard to do sue to the re-starts, I will try and improve that bit as well. I am hoping the a release should be out over the weekend with a fix in for at least the unnecessary re-starting.
