### ISSUE TITLE
I have a problem with type Deeclaration

### ISSUE THREAD

**Issue by CristopherBenavides** [nawforce/apex-assist#3]
I execute this command in palette command: SFDX: Refresh SObject Definitions.
And vscode show me 303 errors similar to picture.

This error is show in the terminal (APEX ASSIST):

"path":"c:\\Users\\S4G\\Documents\\Homeserve\\Entornos\\HS_GitHub\\force-app\\main\\default\\classes\\AlbaranDeleteReviewDateWorkerTest.cls","diagnostic":{"category":{"$type":"DiagnosticCategory","value":"Missing"},"location":{"startLine":60,"startPosition":18,"endLine":60,"endPosition":121},"message":"No type declaration found for 'WorkOrder'"}},{"$type":"com.nawforce.common.diagnostics.Issue","path":"c:\\Users\\S4G\\Documents\\Homeserve\\Entornos\\HS_GitHub\\force-app\\main\\default\\classes\\AlbaranDeleteReviewDateWorkerTest.cls","diagnostic":{"category":{"$type":"DiagnosticCategory","value":"Missing"},"location":{"startLine":60,"startPosition":23,"endLine":60,"endPosition":121},"message":"No type declaration found for 'WorkOrder'"}},{"$type":"com.nawforce.common.diagnostics.Issue","path":"c:\\Users\\S4G\\Documents\\Homeserve\\Entornos\\HS_GitHub\\force-app\\main\\default\\classes\\AlbaranDeleteReviewDateWorkerTest.cls","diagnostic":{"category":{"$type":"DiagnosticCategory","value":"Missing"},"location":{"startLine":48,"startPosition":17,"endLine":48,"endPosition":53},"message":"No type declaration found for 'WorkType'"}},{"$type":"com.nawforce.common.diagnostics.Issue","path":"c:\\Users\\S4G\\Documents\\Homeserve\\Entornos\\HS_GitHub\\force-app\\main\\default\\classes\\AlbaranDeleteReviewDateWorkerTest.cls","diagnostic":{"category":{"$type":"DiagnosticCategory",

![image](https://user-images.githubusercontent.com/72565441/123783232-70ae3c80-d8d6-11eb-857d-6300a0fc3201.png)

Can you help me to solve this? 

Thanks

**Comment by nawforce** [comment]
The extension does make use of the 'Refresh SObject Definitions' that get downloaded, how this works is really specific to the Salesforce extensions only.  

The objects that are missing are from Field Service Lightning, I have recently added support for these as standard in the extension but that version is not yet available. I am hoping to release a new version fairly shorty, within a couple of weeks, so I will comment here when that is available.

**Comment by nawforce** [comment]
This issue should now be fixed, the latest includes all the definitions needed for FSL.
