### ISSUE TITLE
Failed to download metadata - Error: query chunk: ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by PawelWozniak** [nawforce/apex-assist#37]
When I want to use "Assist: Download metadata from org" then I am getting an error:
Failed to download metadata - Error: query chunk: ENOENT: no such file or directory, open
![obraz](https://user-images.githubusercontent.com/5740564/221521350-1a58bbe4-4164-4380-84c0-6509f9d87b41.png)

What I see in log at trace level:
Failed to download metadata
scala.scalajs.js.JavaScriptException: Error: query chunk: ENOENT: no such file or directory, open 'c:\Users\pwozn\\.vscode\extensions\partner.wsdl.xml'
  at {anonymous}()@Error: query chunk: ENOENT: no such file or directory, open 'c:\Users\pwozn\\.vscode\extensions\partner.wsdl.xml'(Unknown Source)

Have I missed some configuration step?
There was no such issue in 1.x series of this plugin.

sfdx-cli/7.188.1 win32-x64 node-v18.13.0
vscode 1.75.1
Apex Assist v2.0.0

**Comment by nawforce** [comment]
Thanks for raising this. I did some webpack work in this release that I think may have broken this, I will take a look in next few days.

**Comment by nawforce** [comment]
Fixed in 2.0.1

**Comment by PawelWozniak** [comment]
Thank you @nawforce. I confirm that it works fine now.
