### ISSUE TITLE
Unknown field 'ShouldAbortRun__c' on SObject 'Schema.RollupControl__mdt'

### ISSUE THREAD

**Issue by jamessimone** [nawforce/apex-assist#5]
If the field being referenced is defined in your `sfdx-project.json` but it's _not_ defined in the `packageDirectory` where the field is being referenced, this error pops up. I _almost_ convinced myself to copy the metadata folders where I am referencing these fields purely to get rid of this error, but I wanted to check with you first.

**Comment by nawforce** [comment]
Thanks for raising this, It's a bug in the way I am handling CMDT, the extension at plugins/CustomObjectRollupLogger/objects/RollupControl__mdt is being treated as though it was defining a new CMDT type which then has the effect of hiding the original fields. 

I will take a look at it today and see if I can get an update out as this might hit quite a few people.

**Comment by nawforce** [comment]
That should be fixed now in 1.3.2.

I have added some warnings against sfdx-project.json for when packaged metadata that is not accessible. A couple of these warnings showing apex-rollup you could get rid of by using the package & versionNumber format to declare the dependencies.

Practically it makes no difference at the moment but in later versions I expect to tighten up the processing model so dependencies are considered. Currently the analysis is still using 'deploy order' to structure things, so as long as your packageDirectories are ordered well it should resolve OK.

**Comment by jamessimone** [comment]
awesome, I'll have a look. clearing out the last of those warnings will be awesome!

**Comment by jamessimone** [comment]
Can confirm - this worked great! Thanks again.
