### ISSUE TITLE
Java.exe Window hangs - Windows 10, VSCode Latest Version, Java 15.0.1

### ISSUE THREAD

**Issue by apexuser1** [nawforce/apex-assist#7]
Hi, 

the Java.exe window hands when I open VScode.  The Output log contains the below and when I select "Assist: Show Dependency Graph" nothing happens.  I'm sure it is a user/config issue but grateful for any help.

Thanks.

Spawning 'java -Xmx1024m -Dfile.encoding=UTF-8 -cp jars/apexlink-2.2.3.jar com.nawforce.apexlink.cmds.Server'
Client: [debug] Sent: {"jsonrpc":"2.0","id":"f5474c56-f386-4ed4-a2b7-13008c2e42ad","method":"version","params":{}}
Client: [debug] Sent: {"jsonrpc":"2.0","id":"94e12226-8740-40f9-bd6d-c4afc14e1095","method":"open","params":["c:\\Users\\ianha\\Dropbox\\My Documents\\Utilligent\\Salesforce\\serviceplus-core-project"]}

**Comment by nawforce** [comment]
Thanks for reporting this, unfortunately that log does not give us much to go on other than it had hung during the startup.

There is a small command line built into the jar, could you try running that on your project to see if we can get an error. To do this try running:

`java -jar %USERPROFILE%\.vscode\extensions\kevinjones.apex-assist-1.5.0/jars/apexlink-2.2.3.jar -debug c:\Users\ianha\Dropbox\My Documents\Utilligent\Salesforce\serviceplus-core-project`

I will try setup an environment to replicate yours and see if I reproduce.

**Comment by apexuser1** [comment]
Hi Kevin,

Thanks for taking a look.  Please find attached the output of the command.

Regards

Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.

________________________________

**Comment by nawforce** [comment]
Hi Ian, 

Thanks for the log. It is showing a problem with sp_etl_ETL_ImportError.cls to do with non-ASCII character handling. This might be a false positive as you are on Windows. Could you try and re-run with -Dfile.encoding=UTF-8 on the command line as well just to be sure.

That error should not have caused a hang from what I can see so I will work on getting a more debug visible in VSCode to see if we can get to the bottom of this.

**Comment by apexuser1** [comment]
Hi Kevin

When I try that either with or without -debug and I also tried -Dfile.encoding="UTF-8". I get:

Multiple arguments provided, expected workspace directory, '-Dfile.encoding=UTF-8, c:\Users\ianha\Dropbox\My Documents\Utilligent\Salesforce\serviceplus-core-project'}

Regards

Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.
________________________________

**Comment by apexuser1** [comment]
Hi Kevin

Do you need me to try anything else?

Regards

Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.
________________________________

**Comment by nawforce** [comment]
Hi Ian.

Sorry for delay in getting back to you, had a busy week at work. I should have mentioned that the -Dfile.encoding=UTF-8 needs to go before the -jar argument. This ordering work for me.

`java -Dfile.encoding=UTF-8 -jar %USERPROFILE%\.vscode\extensions\kevinjones.apex-assist-1.5.0/jars/apexlink-2.2.3.jar -debug Documents\forceapp`

I am pretty sure not having the UTF-8 setting is what caused the exception when you tried it before, so likely I need to do some work to see if we can get some more debug from the VSCode extension to help narrow down why it is hanging. Given the command line works OK it likely something in the communication layer between VSCode and Java but I don't really have any theory as to what that might be. I will try and get you an update in a few days to try.

**Comment by apexuser1** [comment]
Hi Kevin,

NP.

Here is the new debug file.

Regards

Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.

________________________________

**Comment by nawforce** [comment]
Thanks for that. I have managed to reproduce the problem using Java 15.0.1, not sure on cause just yet but looks like it is likely something to do with how I start Java from what I can see so far.

**Comment by apexuser1** [comment]
Thanks for the update.  Glad you can reproduce - lucky you!  Let me know if we can do anything to help you resolve.

Regards

Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.
________________________________

**Comment by nawforce** [comment]
I have created a version with a workaround for the issue and a some extra debug just in case this does not resolve it. If you could give it a try that would be great. You can download the vsix file for this from https://drive.google.com/file/d/1ToLPrN498JROOwovYkAkVpTKgGuA4RFH/view?usp=sharing.

If you have not installed an extension from a vsix file before there are some instructions over at https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix. 

I need to do a bit more testing of the workaround but once complete I will release a new version to the marketplace which will replace this one for you when it lands.

**Comment by apexuser1** [comment]
Hi Kevin,

I'm unable to download as below - I think you need to check the link/share setttings

Regards

[cid:c60f5078-f412-43fd-a09e-411c55a37466]

Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.
________________________________

**Comment by nawforce** [comment]
Sorry that was probably due to me changing the link after I initially posted it, if you try this one it should be OK, I can download from browser that is not logged into the Google account.

https://drive.google.com/file/d/1Wv01JcO_Kd15wvVV7y5HYb_QCtj-HN2F/view?usp=sharing

**Comment by apexuser1** [comment]
Thanks, the problem is fixed.  It installed ok with the below warnings. And it it seems to be working ok - only played with it for 5 mins.

Let me know if you need anything else.

[cid:cf4fd260-7b2e-43cc-b8aa-1753ee55f11d]



Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.
________________________________

**Comment by nawforce** [comment]
I pushed out an update for this last week so should be fully resolved now.

**Comment by apexuser1** [comment]
Hi Kevin

It appears that there may be a problem with this version.  I can reproduce as below and my colleague had the same issue on a separate machine.

To reproduce:

  1.  Verify V1.5.1 is running ok using "Assist: Show Dependency Graph"
  2.  Upgrade to V1.6.0
  3.  Exit VS Code
  4.  Restart VSCode
  5.  Verify V1.6.0 is running ok - as per 1. It this case nothing happens, not the same as the original issue where the server hung. Nothing obvious happens in the case. I have included the output below, which show the server was started.
  6.  Unistall V1.6.0
  7.  VS Code Reload
  8.  Install V1.5.1 fron VSIX file provide
  9.  Verify V1.5.1 is running ok using "Assist: Show Dependency Graph"

Please let me know if you need any further information - I'm going on leave AM on 8th Feb for 3 weeks and will not have access my "developer" machine.

Regards


[cid:3379207b-cbc0-43f8-ac70-839d2cf335bd]
Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.
________________________________

**Comment by nawforce** [comment]
Hi Ian, thanks letting me know. Looks like I have an issue with .forceIgnore handling that can cause this on Windows. I have a fix for it so just need to get it packaged up, which should happen in next day or so.

**Comment by apexuser1** [comment]
Hi Kevin,

good that you found the issue so quickly!

I won't have access to a developer machine to the EOM to test.

Regards

Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.
________________________________

**Comment by apexuser1** [comment]
Hi Kevin

Trust that you are well.

I was wondering is there any way for Apex Assist to ignore warnings for certain code fragments, e.g. something like @SuppressWarnings('PMD.UnusedLocalVariable')

Regards

Ian Harrop | Principal
TWG P/L
M +61 (0)419 319 726

___________________________________________________________________________________

This e-mail transmission is intended only for the addressee and may contain confidential or privileged information. Confidentiality and privilege are not waived if you are not the intended recipient of this e-mail, nor may you use, review, disclose, disseminate or copy any information contained in or attached to it. If you received this e-mail in error please delete it and any attachments and notify the sender immediately by reply e-mail. The sender does not warrant that any attachments are free from viruses or other defects. You assume all liability for any loss, damage or other consequences which may arise from opening or using the attachments.
________________________________
