### ISSUE TITLE
Feature request:  include LWCs, VF pages and flows in the dependency graph

### ISSUE THREAD

**Issue by Fernando-Fernandez** [nawforce/apex-assist#9]
Kevin, would it be possible to include LWCs, VF pages and screen flows in the dependency graph, possibly color-coded differently?

The idea is to be able to easily see what LWCs/pages/flows are using a certain Apex controller class.

If possible, would that be accomplished by changing the ApexDefinitionFilter class?
I've noticed the following line:
`  override val pattern: String = "**/*.{cls,trigger}"
`
Presumably, it could be edited to include other extensions, no?

**Comment by nawforce** [comment]
At the moment we have full handling for VF pages/components & know a little bit about flows but we don't look at the metadata for LWCs so only some of this is possible today without working out how to extract dependencies from flows/LWC metadata. The dependency graph pulls data from the Java server which at the moment only returns information about classes & triggers, so the code on that API is the bit that would need updating. 

A colleague of mine is doing some work on LWC dependencies so we might be able to build on that. I have rather a lot of work in progress at the moment so its not likely I will be able to look at this in the next couple of months but happy to leave here if anyone fancies having a go at extending for this.
